// WARNING: This file was automatically generated by "no.item.xp.codegen". You may lose your changes if you edit it.
export interface Article {
  /**
   * Image
   */
  unsplashId?: Array<string> | string;

  /**
   * GraphQL name. Also used for separating unions in TypeScript
   */
  __typename?: "no_item_unsplash_Article_Data";
}
